"""create domain schema

Revision ID: 0002_phase4_domain_schema
Revises: 0001_phase3_baseline
Create Date: 2026-07-23 17:08:42.956332
"""

from collections.abc import Sequence

import app.database.types
import sqlalchemy as sa
from alembic import op

revision: str = "0002_phase4_domain_schema"
down_revision: str | Sequence[str] | None = "0001_phase3_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_visible", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_categories_sort_order_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_categories_slug"), ["slug"], unique=True)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column(
            "created_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_slug"), ["slug"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", app.database.types.UTCDateTime(), nullable=True),
        sa.Column("password_changed_at", app.database.types.UTCDateTime(), nullable=True),
        sa.Column("last_login_at", app.database.types.UTCDateTime(), nullable=True),
        sa.Column(
            "created_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "failed_login_attempts >= 0", name=op.f("ck_users_failed_login_attempts_nonnegative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=True),
        sa.Column("entity_id", sa.String(length=100), nullable=True),
        sa.Column("result", sa.String(length=50), nullable=False),
        sa.Column(
            "timestamp",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("safe_metadata", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index("ix_audit_logs_action", ["action"], unique=False)
        batch_op.create_index("ix_audit_logs_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("ix_audit_logs_timestamp", ["timestamp"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_audit_logs_user_timestamp", ["user_id", "timestamp"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", app.database.types.UTCDateTime(), nullable=False),
        sa.Column("absolute_expires_at", app.database.types.UTCDateTime(), nullable=False),
        sa.Column("revoked_at", app.database.types.UTCDateTime(), nullable=True),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("csrf_secret_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(
            "ix_sessions_revoked_expiry", ["revoked_at", "expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_session_token_hash"), ["session_token_hash"], unique=True
        )
        batch_op.create_index("ix_sessions_user_expiry", ["user_id", "expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "software",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("short_description", sa.String(length=500), nullable=False),
        sa.Column("full_description", sa.Text(), nullable=True),
        sa.Column("developer_name", sa.String(length=180), nullable=True),
        sa.Column("official_website_url", sa.String(length=2048), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("license_name", sa.String(length=180), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("icon_path", sa.String(length=500), nullable=True),
        sa.Column("supported_os", sa.Text(), nullable=True),
        sa.Column("system_requirements", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "hidden",
                "archived",
                "disabled",
                name="software_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum(
                "public",
                "unlisted",
                "private",
                name="software_visibility",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="private",
            nullable=False,
        ),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("published_at", app.database.types.UTCDateTime(), nullable=True),
        sa.Column("archived_at", app.database.types.UTCDateTime(), nullable=True),
        sa.Column(
            "created_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_software_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_software")),
    )
    with op.batch_alter_table("software", schema=None) as batch_op:
        batch_op.create_index(
            "ix_software_category_status", ["category_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_software_featured_updated", ["is_featured", "updated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_software_name"), ["name"], unique=False)
        batch_op.create_index(
            "ix_software_public_listing", ["status", "visibility", "updated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_software_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_software_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_software_visibility"), ["visibility"], unique=False)

    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("software_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column(
            "release_channel",
            sa.Enum(
                "stable",
                "beta",
                "alpha",
                "nightly",
                "legacy",
                name="release_channel",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="stable",
            nullable=False,
        ),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("changelog", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "archived",
                "disabled",
                name="release_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("published_at", app.database.types.UTCDateTime(), nullable=True),
        sa.Column(
            "created_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["software_id"],
            ["software.id"],
            name=op.f("fk_releases_software_id_software"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
        sa.UniqueConstraint(
            "software_id", "version", "release_channel", name="uq_releases_software_version_channel"
        ),
    )
    with op.batch_alter_table("releases", schema=None) as batch_op:
        batch_op.create_index(
            "ix_releases_software_date", ["software_id", "release_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_releases_software_id"), ["software_id"], unique=False)
        batch_op.create_index(
            "ix_releases_software_status", ["software_id", "status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_releases_status"), ["status"], unique=False)
        batch_op.create_index(
            "uq_releases_one_current_stable_per_software",
            ["software_id"],
            unique=True,
            sqlite_where=sa.text("is_current = 1 AND release_channel = 'stable'"),
            postgresql_where=sa.text("is_current IS TRUE AND release_channel = 'stable'"),
        )

    op.create_table(
        "software_tags",
        sa.Column("software_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["software_id"],
            ["software.id"],
            name=op.f("fk_software_tags_software_id_software"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_software_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("software_id", "tag_id", name=op.f("pk_software_tags")),
    )
    op.create_table(
        "release_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_uuid", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("display_filename", sa.String(length=500), nullable=False),
        sa.Column("storage_filename", sa.String(length=255), nullable=False),
        sa.Column("relative_storage_path", sa.String(length=1000), nullable=False),
        sa.Column("file_extension", sa.String(length=20), nullable=False),
        sa.Column("detected_mime_type", sa.String(length=255), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "architecture",
            sa.Enum(
                "x64",
                "x86",
                "arm64",
                "universal",
                "other",
                name="file_architecture",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column(
            "package_type",
            sa.Enum(
                "installer",
                "portable",
                "archive",
                "msi",
                "other",
                name="file_package_type",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("platform", sa.String(length=100), nullable=False),
        sa.Column("edition", sa.String(length=180), nullable=True),
        sa.Column("download_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "quarantine",
                "ready",
                "published",
                "disabled",
                "archived",
                "rejected",
                name="file_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="quarantine",
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum(
                "public",
                "unlisted",
                "private",
                name="file_visibility",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="private",
            nullable=False,
        ),
        sa.Column(
            "uploaded_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("published_at", app.database.types.UTCDateTime(), nullable=True),
        sa.Column("disabled_at", app.database.types.UTCDateTime(), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "signature_status",
            sa.Enum(
                "unknown",
                "valid",
                "invalid",
                "unsigned",
                "not_checked",
                name="signature_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "scanner_status",
            sa.Enum(
                "not_scanned",
                "clean",
                "infected",
                "error",
                "unavailable",
                name="scanner_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="not_scanned",
            nullable=False,
        ),
        sa.Column("scanner_details", sa.String(length=500), nullable=True),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.database.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "download_count >= 0", name=op.f("ck_release_files_download_count_nonnegative")
        ),
        sa.CheckConstraint(
            "file_size_bytes >= 0", name=op.f("ck_release_files_file_size_nonnegative")
        ),
        sa.CheckConstraint("length(sha256) = 64", name=op.f("ck_release_files_sha256_length")),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_release_files_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_release_files")),
        sa.UniqueConstraint(
            "relative_storage_path", name=op.f("uq_release_files_relative_storage_path")
        ),
        sa.UniqueConstraint("storage_filename", name=op.f("uq_release_files_storage_filename")),
    )
    with op.batch_alter_table("release_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_release_files_public_uuid"), ["public_uuid"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_release_files_release_id"), ["release_id"], unique=False
        )
        batch_op.create_index(
            "ix_release_files_release_status", ["release_id", "status"], unique=False
        )
        batch_op.create_index("ix_release_files_sha256", ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_release_files_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_release_files_status_visibility", ["status", "visibility"], unique=False
        )
        batch_op.create_index("ix_release_files_uploaded_at", ["uploaded_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_release_files_visibility"), ["visibility"], unique=False
        )

    op.create_table(
        "download_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("release_file_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("download_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("successful_download_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("blocked_download_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "blocked_download_count >= 0", name=op.f("ck_download_stats_blocked_count_nonnegative")
        ),
        sa.CheckConstraint(
            "download_count >= 0", name=op.f("ck_download_stats_download_count_nonnegative")
        ),
        sa.CheckConstraint(
            "successful_download_count >= 0",
            name=op.f("ck_download_stats_successful_count_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["release_file_id"],
            ["release_files.id"],
            name=op.f("fk_download_stats_release_file_id_release_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_download_stats")),
        sa.UniqueConstraint("release_file_id", "date", name="uq_download_stats_file_date"),
    )
    with op.batch_alter_table("download_stats", schema=None) as batch_op:
        batch_op.create_index("ix_download_stats_date", ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_download_stats_release_file_id"), ["release_file_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("download_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_download_stats_release_file_id"))
        batch_op.drop_index("ix_download_stats_date")

    op.drop_table("download_stats")
    with op.batch_alter_table("release_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_release_files_visibility"))
        batch_op.drop_index("ix_release_files_uploaded_at")
        batch_op.drop_index("ix_release_files_status_visibility")
        batch_op.drop_index(batch_op.f("ix_release_files_status"))
        batch_op.drop_index("ix_release_files_sha256")
        batch_op.drop_index("ix_release_files_release_status")
        batch_op.drop_index(batch_op.f("ix_release_files_release_id"))
        batch_op.drop_index(batch_op.f("ix_release_files_public_uuid"))

    op.drop_table("release_files")
    op.drop_table("software_tags")
    with op.batch_alter_table("releases", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_releases_one_current_stable_per_software",
            sqlite_where=sa.text("is_current = 1 AND release_channel = 'stable'"),
            postgresql_where=sa.text("is_current IS TRUE AND release_channel = 'stable'"),
        )
        batch_op.drop_index(batch_op.f("ix_releases_status"))
        batch_op.drop_index("ix_releases_software_status")
        batch_op.drop_index(batch_op.f("ix_releases_software_id"))
        batch_op.drop_index("ix_releases_software_date")

    op.drop_table("releases")
    with op.batch_alter_table("software", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_software_visibility"))
        batch_op.drop_index(batch_op.f("ix_software_status"))
        batch_op.drop_index(batch_op.f("ix_software_slug"))
        batch_op.drop_index("ix_software_public_listing")
        batch_op.drop_index(batch_op.f("ix_software_name"))
        batch_op.drop_index("ix_software_featured_updated")
        batch_op.drop_index("ix_software_category_status")

    op.drop_table("software")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index("ix_sessions_user_expiry")
        batch_op.drop_index(batch_op.f("ix_sessions_session_token_hash"))
        batch_op.drop_index("ix_sessions_revoked_expiry")
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_user_timestamp")
        batch_op.drop_index(batch_op.f("ix_audit_logs_user_id"))
        batch_op.drop_index("ix_audit_logs_timestamp")
        batch_op.drop_index("ix_audit_logs_entity")
        batch_op.drop_index("ix_audit_logs_action")

    op.drop_table("audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_slug"))

    op.drop_table("tags")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_slug"))

    op.drop_table("categories")
    # ### end Alembic commands ###
